### PR TITLE
Pass data through render into render methods

### PR DESCRIPTION
**Pull request by chrisinajar**
Allow passing arbitrary extra data into `Sour.render` and pass it through to the route render method.

Thoughts?

### CODE REVIEW

**Comment by bendrucker** [comment]
Yup this should absolutely exist, working on it either today or Sunday

**Comment by ajoslin** [comment]
Looking forward to this too. Let us know any way we can help.

**Comment by bendrucker** [comment]
👍  Didn't get to it this weekend but I can play with it a bit during work and give you guys a fully working branch to try. It's 85% of the way there.

**Comment by bendrucker** [comment]
This is available in #6

**Pull request closed without merging**
